edition = "2021"
color = "Always"
newline_style = "Unix"
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
use_small_heuristics = "default"
use_try_shorthand = true
wrap_comments = true
comment_width = 80
normalize_comments = true
